### PR TITLE
Typescript

### PR DESCRIPTION
**Pull request by pelikhan**
Moving to typescript and slimming down the library to just a hook. Still fighting the build systems to be able to get the demo app running again.

### CODE REVIEW

**Comment by pelikhan** [comment]
may be a bit extreme of a refactoring but smaller is better.

**Comment by nbudin** [comment]
Hi Peli, thanks for making this.  I do agree it's a little extreme.  I would like to keep the BlocklyWorkspace component, since many users of this library are relatively new to React and I think would find the requirement to use a ref and a hook intimidating.  Would you mind putting it back?

**Comment by pelikhan** [comment]
I’ll bring it back. I was always told when you prune a tree, cut hard :)

________________________________

**Comment by nbudin** [comment]
Closed in favor of #68 which is a more minimal version of this.

**Pull request closed without merging**
