### PR TITLE
Upgrade blockly to v3.20200625.1

### PR DESCRIPTION
**Pull request by mastanca**
Closes #24 

Upgrade blockly to [v3.20200625.1](https://github.com/google/blockly/releases/tag/3.20200625.1)

Works out of the box, no breaking changes

screenshot

### CODE REVIEW

**Comment by nbudin** [comment]
Awesome, thanks @mastanca!  This is now released to npm as version 5.1.0.

**Comment by samelhusseini** [comment]
I was hoping I would catch you before you pushed this. 
I just released a patch that fixes a regression in field dropdowns with images. https://github.com/google/blockly/issues/4015

**Comment by nbudin** [comment]
Whoops, thanks @samelhusseini - I'll put out a new one.  Is it worth yanking 5.1.0 out?

**Comment by samelhusseini** [comment]
We don't generally pull out versions, even if there's a regression in there. I imagine most people will have their versions set to the latest major / minor anyway.

**Comment by nbudin** [comment]
OK, sounds good.  5.1.1 is now out with the dependency updated.

**Comment by samelhusseini** [comment]
Thank you!

**Pull request merged**
