### PR TITLE
Optimize render

### PR DESCRIPTION
**Pull request by SerSerch**
Hello!
I started working on react-native-blockly and decided to figure out how it works in your module. I have optimized the rendering.

If you need it, I will optimize useBlocklyWorkspace next time.

(after optimize with memo Editor)
---
render

### CODE REVIEW

**Comment by nbudin** [comment]
Hi @SerSerch, thanks for your patch!  I'm not totally sure I understand the goal of these changes.  Could you explain what this is doing?

**Comment by SerSerch** [comment]
each props change or new state causes the entire BlocklyWorkspaceComponent to be rerendered.
this affects rerendering performance and loads the browser by requiring the div and the entire svg to be redrawn again and again.

[memo](https://react.dev/reference/react/memo) prohibits extra renders if props or state have not changed

**Comment by nbudin** [comment]
I don't think this is correct.  Re-rendering doesn't require the browser to redraw the SVG each time, because of virtual DOM diffing: https://dev.to/sakethkowtha/why-react-components-re-render-every-time-when-state-changes-explained-3jck

**Comment by SerSerch** [comment]
yes, props or state changes cause Virtual DOM changes. If it has changed, the UI change is called.

create a button that will change state. then add log to Test components
```js
const TestComponent = () => {
  console.log("new render component", new Date());
  return <div />;
}

const TestMemo = React.memo(() => {
  console.log("new render memo", new Date());
  return <div />;
});

function TestPage() {
  const [serialState, setSerialState] = useState<boolean>(true);

return (
  <>
    <button
          onClick={() =>
            setSerialState(!serialState);
          }
        >
          {serialState ? "TRUE" : "FALSE"}
        </button>
        
        <TestMemo />
        <TestComponent />
   </>
);
}
```
image

**Comment by nbudin** [comment]
Yes, it's true that the component will render again, but this does not cause the browser to redraw any div, svg, or other elements unless their content has actually changed, which it won't in most cases in react-blockly.

**Comment by SerSerch** [comment]
(c) https://react.dev/reference/react/memo#skipping-re-rendering-when-props-are-unchanged

React normally re-renders a component whenever its parent re-renders. With memo, you can create a component that React will not re-render when its parent re-renders so long as its new props are the same as the old props.
By using memo, you are telling React that your component complies with this requirement, so React doesn’t need to re-render as long as its props haven’t changed.

**Comment by nbudin** [comment]
Thanks for clarifying.

Re-rendering is not usually a performance problem in and of itself, because of the aforementioned virtual DOM diffing mechanism.  For most applications, this should be more than sufficient to make react-blockly perform well.

If your application is so sensitive to performance issues that this does make a substantial difference for you, I recommend memoizing the component in your app.  Adding React.memo for everyone is unlikely to provide value for most users and could possibly cause bugs in cases where the comparison function produces false negatives or positives.

**Comment by SerSerch** [comment]
another plus
if you use memo, you can drop the constant useRef for everyone

```
const onXmlChangeRef = React.useRef(onXmlChange);

  React.useEffect(() => {
    onXmlChangeRef.current = onXmlChange;
  }, [onXmlChange]);
  
    const onJsonChangeRef = React.useRef(onJsonChange);
  
  React.useEffect(() => {
    onJsonChangeRef.current = onJsonChange;
  }, [onJsonChange]);
```

**Comment by SerSerch** [comment]
@nbudin ok, if i didn't convince you, but i tried )

**Pull request closed without merging**
