### PR TITLE
feat: work on browsers that dont accept arbitrary dom node names

### PR DESCRIPTION
**Pull request by eordano**

### CODE REVIEW

**Comment by zamber** [comment]
WFM. I don't get the <xml> tag warning any more :).

**Comment by nbudin** [comment]
Hi there, sorry for the delay in reviewing this!  I just tried out the branch and, while I don't get the tag name warnings anymore, I also don't seem to see anything in the toolbox (at least in Chrome).  Looking through the Blockly source code, I don't see any support for the `datatype` attribute that you used.  Does this only work with a modified version of Blockly?

**Comment by zamber** [comment]
@nbudin this sounds correct. I also have trouble with getting the toolbox to work but I blamed my inability to copy over the sample over to our code base. I'll look deeper into it.

**Comment by GAUTAMRAJU15** [comment]
hi nbudin, can you review this pr , i am  also getting these errors , i want to download fresh code :(

**Comment by nbudin** [comment]
@GAUTAMRAJU15 I'd like to, but this patch does not seem to work.  See my comment above.  I'm hoping @eordano can clarify how this is supposed to be used, if not I will have to close it.

**Comment by GAUTAMRAJU15** [comment]
@eordano are you sure it's working ? can you re-check on your end

**Pull request closed without merging**
